In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv('E_Commerce_Dataset.csv')

In [3]:
dataset.head(5)

CustomerID PreferredLoginDevice  CityTier  WarehouseToHome  \
0       50001         Mobile Phone         3              6.0   
1       50002                Phone         1              8.0   
2       50003                Phone         1             30.0   
3       50004                Phone         3             15.0   
4       50005                Phone         1             12.0   

  PreferredPaymentMode  Gender  HourSpendOnApp  NumberOfDeviceRegistered  \
0           Debit Card  Female             3.0                         3   
1                  UPI    Male             3.0                         4   
2           Debit Card    Male             2.0                         4   
3           Debit Card    Male             2.0                         4   
4                   CC    Male             NaN                         3   

     PreferedOrderCat  SatisfactionScore MaritalStatus  NumberOfAddress  \
0  Laptop & Accessory                  2        Single                9   
1              Mobile                  3        Single                7   
2              Mobile                  3        Single                6   
3  Laptop & Accessory                  5        Single                8   
4              Mobile                  5        Single                3   

   Complain  OrderAmountHikeFromlastYear  CouponUsed  OrderCount  \
0         1                         11.0         1.0         1.0   
1         1                         15.0         0.0         1.0   
2         1                         14.0         0.0         1.0   
3         0                         23.0         0.0         1.0   
4         0                         11.0         1.0         1.0   

   DaySinceLastOrder  CashbackAmount  Tenure  Churn  
0                5.0             160     4.0      1  
1                0.0             121     NaN      1  
2                3.0             120     NaN      1  
3                3.0             134     0.0      1  
4                3.0             130     0.0      1

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5630 entries, 0 to 5629
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   CustomerID                   5630 non-null   int64  
 1   PreferredLoginDevice         5630 non-null   object 
 2   CityTier                     5630 non-null   int64  
 3   WarehouseToHome              5379 non-null   float64
 4   PreferredPaymentMode         5630 non-null   object 
 5   Gender                       5630 non-null   object 
 6   HourSpendOnApp               5375 non-null   float64
 7   NumberOfDeviceRegistered     5630 non-null   int64  
 8   PreferedOrderCat             5630 non-null   object 
 9   SatisfactionScore            5630 non-null   int64  
 10  MaritalStatus                5630 non-null   object 
 11  NumberOfAddress              5630 non-null   int64  
 12  Complain                     5630 non-null   int64  
 13  OrderAmountHikeFro

In [5]:
print(dataset.shape)

(5630, 20)


In [6]:
dataset.describe(include='all')

CustomerID PreferredLoginDevice     CityTier  WarehouseToHome  \
count    5630.000000                 5630  5630.000000      5379.000000   
unique           NaN                    3          NaN              NaN   
top              NaN         Mobile Phone          NaN              NaN   
freq             NaN                 2765          NaN              NaN   
mean    52815.500000                  NaN     1.654707        15.639896   
std      1625.385339                  NaN     0.915389         8.531475   
min     50001.000000                  NaN     1.000000         5.000000   
25%     51408.250000                  NaN     1.000000         9.000000   
50%     52815.500000                  NaN     1.000000        14.000000   
75%     54222.750000                  NaN     3.000000        20.000000   
max     55630.000000                  NaN     3.000000       127.000000   

       PreferredPaymentMode Gender  HourSpendOnApp  NumberOfDeviceRegistered  \
count                  5630   5630     5375.000000               5630.000000   
unique                    7      2             NaN                       NaN   
top              Debit Card   Male             NaN                       NaN   
freq                   2314   3384             NaN                       NaN   
mean                    NaN    NaN        2.931535                  3.688988   
std                     NaN    NaN        0.721926                  1.023999   
min                     NaN    NaN        0.000000                  1.000000   
25%                     NaN    NaN        2.000000                  3.000000   
50%                     NaN    NaN        3.000000                  4.000000   
75%                     NaN    NaN        3.000000                  4.000000   
max                     NaN    NaN        5.000000                  6.000000   

          PreferedOrderCat  SatisfactionScore MaritalStatus  NumberOfAddress  \
count                 5630        5630.000000          5630      5630.000000   
unique                   6                NaN             3              NaN   
top     Laptop & Accessory                NaN       Married              NaN   
freq                  2050                NaN          2986              NaN   
mean                   NaN           3.066785           NaN         4.214032   
std                    NaN           1.380194           NaN         2.583586   
min                    NaN           1.000000           NaN         1.000000   
25%                    NaN           2.000000           NaN         2.000000   
50%                    NaN           3.000000           NaN         3.000000   
75%                    NaN           4.000000           NaN         6.000000   
max                    NaN           5.000000           NaN        22.000000   

           Complain  OrderAmountHikeFromlastYear   CouponUsed   OrderCount  \
count   5630.000000                  5365.000000  5374.000000  5372.000000   
unique          NaN                          NaN          NaN          NaN   
top             NaN                          NaN          NaN          NaN   
freq            NaN                          NaN          NaN          NaN   
mean       0.284902                    15.707922     1.751023     3.008004   
std        0.451408                     3.675485     1.894621     2.939680   
min        0.000000                    11.000000     0.000000     1.000000   
25%        0.000000                    13.000000     1.000000     1.000000   
50%        0.000000                    15.000000     1.000000     2.000000   
75%        1.000000                    18.000000     2.000000     3.000000   
max        1.000000                    26.000000    16.000000    16.000000   

        DaySinceLastOrder  CashbackAmount       Tenure        Churn  
count         5323.000000     5630.000000  5366.000000  5630.000000  
unique                NaN             NaN          NaN          NaN  
top                   NaN             Na

In [8]:
dataset.isnull().sum()

CustomerID                       0
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
Tenure                         264
Churn                            0
dtype: int64

In [9]:
print(f'The number of missing value: {dataset.isnull().sum().sum()}')
print(f'The number of rows with missing value: {dataset[dataset.isnull().any(axis=1)].shape[0]}')

The number of missing value: 1856
The number of rows with missing value: 1856


In [10]:
dataset1 = dataset.drop(labels=['CityTier'], axis=1)
titles = list(dataset1.columns)
titles

['CustomerID',
 'PreferredLoginDevice',
 'WarehouseToHome',
 'PreferredPaymentMode',
 'Gender',
 'HourSpendOnApp',
 'NumberOfDeviceRegistered',
 'PreferedOrderCat',
 'SatisfactionScore',
 'MaritalStatus',
 'NumberOfAddress',
 'Complain',
 'OrderAmountHikeFromlastYear',
 'CouponUsed',
 'OrderCount',
 'DaySinceLastOrder',
 'CashbackAmount',
 'Tenure',
 'Churn']

In [11]:
titles[2],titles[9] = titles[9],titles[2]
titles[5],titles[7] = titles[7],titles[5]
titles[6],titles[7] = titles[7],titles[6]
titles

['CustomerID',
 'PreferredLoginDevice',
 'MaritalStatus',
 'PreferredPaymentMode',
 'Gender',
 'PreferedOrderCat',
 'HourSpendOnApp',
 'NumberOfDeviceRegistered',
 'SatisfactionScore',
 'WarehouseToHome',
 'NumberOfAddress',
 'Complain',
 'OrderAmountHikeFromlastYear',
 'CouponUsed',
 'OrderCount',
 'DaySinceLastOrder',
 'CashbackAmount',
 'Tenure',
 'Churn']

In [12]:
final_dataset=dataset1[titles]
final_dataset

CustomerID PreferredLoginDevice MaritalStatus PreferredPaymentMode  \
0          50001         Mobile Phone        Single           Debit Card   
1          50002                Phone        Single                  UPI   
2          50003                Phone        Single           Debit Card   
3          50004                Phone        Single           Debit Card   
4          50005                Phone        Single                   CC   
...          ...                  ...           ...                  ...   
5625       55626             Computer       Married          Credit Card   
5626       55627         Mobile Phone       Married          Credit Card   
5627       55628         Mobile Phone       Married           Debit Card   
5628       55629             Computer       Married          Credit Card   
5629       55630         Mobile Phone       Married          Credit Card   

      Gender    PreferedOrderCat  HourSpendOnApp  NumberOfDeviceRegistered  \
0     Female  Laptop & Accessory             3.0                         3   
1       Male              Mobile             3.0                         4   
2       Male              Mobile             2.0                         4   
3       Male  Laptop & Accessory             2.0                         4   
4       Male              Mobile             NaN                         3   
...      ...                 ...             ...                       ...   
5625    Male  Laptop & Accessory             3.0                         2   
5626    Male             Fashion             3.0                         5   
5627    Male  Laptop & Accessory             3.0                         2   
5628    Male  Laptop & Accessory             4.0                         5   
5629    Male  Laptop & Accessory             3.0                         2   

      SatisfactionScore  WarehouseToHome  NumberOfAddress  Complain  \
0                     2              6.0                9         1   
1                     3              8.0                7         1   
2                     3             30.0                6         1   
3                     5             15.0                8         0   
4                     5             12.0                3         0   
...                 ...              ...              ...       ...   
5625                  1             30.0                6         0   
5626                  5             13.0                6         0   
5627                  4             11.0                3         1   
5628                  4              9.0                4         0   
5629                  3             15.0                4         0   

      OrderAmountHikeFromlastYear  CouponUsed  OrderCount  DaySinceLastOrder  \
0                            11.0         1.0         1.0                5.0   
1                            15.0         0.0         1.0                0.0   
2                            14.0         0.0         1.0                3.0   
3                            23.0         0.0         1.0                3.0   
4                            11.0         1.0         1.0                3.0   
...                           ...         ...         ...                ...   
5625                         18.0         1.0         2.0                4.0   
5626                         16.0         1.0         2.0                NaN   
5627                         21.0         1.0         2.0                4.0   
5628                         15.0         2.0         2.0                9.0   
5629                         13.0         2.0         2.0                3.0   

      CashbackAmount  Tenure  Churn  
0                160     4.0      1  
1                121     NaN      1  
2                120     NaN      1  
3                134     0.0      1  
4                130     0.0      1  
...              ...     ...    ...  
5625             151    10.0      0  
5626             225    13.0      0  


In [13]:
final_dataset.keys()

Index(['CustomerID', 'PreferredLoginDevice', 'MaritalStatus',
       'PreferredPaymentMode', 'Gender', 'PreferedOrderCat', 'HourSpendOnApp',
       'NumberOfDeviceRegistered', 'SatisfactionScore', 'WarehouseToHome',
       'NumberOfAddress', 'Complain', 'OrderAmountHikeFromlastYear',
       'CouponUsed', 'OrderCount', 'DaySinceLastOrder', 'CashbackAmount',
       'Tenure', 'Churn'],
      dtype='object')

In [14]:
x = final_dataset.iloc[:, :-1].values
y = final_dataset.iloc[:, -1].values

# Handling Missing values

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 6:18])
x[:, 6:18] = imputer.transform(x[:, 6:18])

In [16]:
pd.DataFrame(x, columns=['CustomerID', 'PreferredLoginDevice', 'MaritalStatus',
       'PreferredPaymentMode', 'Gender', 'PreferedOrderCat', 'HourSpendOnApp',
       'NumberOfDeviceRegistered', 'SatisfactionScore', 'WarehouseToHome',
       'NumberOfAddress', 'Complain', 'OrderAmountHikeFromlastYear',
       'CouponUsed', 'OrderCount', 'DaySinceLastOrder', 'CashbackAmount',
       'Tenure',])

CustomerID PreferredLoginDevice MaritalStatus PreferredPaymentMode  \
0         50001         Mobile Phone        Single           Debit Card   
1         50002                Phone        Single                  UPI   
2         50003                Phone        Single           Debit Card   
3         50004                Phone        Single           Debit Card   
4         50005                Phone        Single                   CC   
...         ...                  ...           ...                  ...   
5625      55626             Computer       Married          Credit Card   
5626      55627         Mobile Phone       Married          Credit Card   
5627      55628         Mobile Phone       Married           Debit Card   
5628      55629             Computer       Married          Credit Card   
5629      55630         Mobile Phone       Married          Credit Card   

      Gender    PreferedOrderCat HourSpendOnApp NumberOfDeviceRegistered  \
0     Female  Laptop & Accessory            3.0                      3.0   
1       Male              Mobile            3.0                      4.0   
2       Male              Mobile            2.0                      4.0   
3       Male  Laptop & Accessory            2.0                      4.0   
4       Male              Mobile       2.931535                      3.0   
...      ...                 ...            ...                      ...   
5625    Male  Laptop & Accessory            3.0                      2.0   
5626    Male             Fashion            3.0                      5.0   
5627    Male  Laptop & Accessory            3.0                      2.0   
5628    Male  Laptop & Accessory            4.0                      5.0   
5629    Male  Laptop & Accessory            3.0                      2.0   

     SatisfactionScore WarehouseToHome NumberOfAddress Complain  \
0                  2.0             6.0             9.0      1.0   
1                  3.0             8.0             7.0      1.0   
2                  3.0            30.0             6.0      1.0   
3                  5.0            15.0             8.0      0.0   
4                  5.0            12.0             3.0      0.0   
...                ...             ...             ...      ...   
5625               1.0            30.0             6.0      0.0   
5626               5.0            13.0             6.0      0.0   
5627               4.0            11.0             3.0      1.0   
5628               4.0             9.0             4.0      0.0   
5629               3.0            15.0             4.0      0.0   

     OrderAmountHikeFromlastYear CouponUsed OrderCount DaySinceLastOrder  \
0                           11.0        1.0        1.0               5.0   
1                           15.0        0.0        1.0               0.0   
2                           14.0        0.0        1.0               3.0   
3                           23.0        0.0        1.0               3.0   
4                           11.0        1.0        1.0               3.0   
...                          ...        ...        ...               ...   
5625                        18.0        1.0        2.0               4.0   
5626                        16.0        1.0        2.0          4.543491   
5627                        21.0        1.0        2.0               4.0   
5628                        15.0        2.0        2.0               9.0   
5629                        13.0        2.0        2.0               3.0   

     CashbackAmount     Tenure  
0             160.0        4.0  
1             121.0  10.189899  
2             120.0  10.189899  
3             134.0        0.0  
4             130.0        0.0  
...             ...        ...  
5625          151.0       10.0  
5626          225.0       13.0  
5627          186.0        1.0  
5628          179.0       23.0  
5629          169.0        8.0  

[5630 rows x 18 columns]

# Encoding categorical data using One Hot Encoding

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,3,4,5])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [18]:
print(x)

[[0.0 1.0 0.0 ... 5.0 160.0 4.0]
 [0.0 0.0 1.0 ... 0.0 121.0 10.189899366380917]
 [0.0 0.0 1.0 ... 3.0 120.0 10.189899366380917]
 ...
 [0.0 1.0 0.0 ... 4.0 186.0 1.0]
 [1.0 0.0 0.0 ... 9.0 179.0 23.0]
 [0.0 1.0 0.0 ... 3.0 169.0 8.0]]


In [19]:
pd.DataFrame(data=x)

0    1    2    3    4    5    6    7    8    9   ...   24    25   26  \
0     0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  2.0   6.0  9.0   
1     0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  3.0   8.0  7.0   
2     0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  3.0  30.0  6.0   
3     0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  5.0  15.0  8.0   
4     0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  ...  5.0  12.0  3.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...   
5625  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  30.0  6.0   
5626  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  5.0  13.0  6.0   
5627  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  4.0  11.0  3.0   
5628  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  4.0   9.0  4.0   
5629  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  3.0  15.0  4.0   

       27    28   29   30        31     32         33  
0     1.0  11.0  1.0  1.0       5.0  160.0        4.0  
1     1.0  15.0  0.0  1.0       0.0  121.0  10.189899  
2     1.0  14.0  0.0  1.0       3.0  120.0  10.189899  
3     0.0  23.0  0.0  1.0       3.0  134.0        0.0  
4     0.0  11.0  1.0  1.0       3.0  130.0        0.0  
...   ...   ...  ...  ...       ...    ...        ...  
5625  0.0  18.0  1.0  2.0       4.0  151.0       10.0  
5626  0.0  16.0  1.0  2.0  4.543491  225.0       13.0  
5627  1.0  21.0  1.0  2.0       4.0  186.0        1.0  
5628  0.0  15.0  2.0  2.0       9.0  179.0       23.0  
5629  0.0  13.0  2.0  2.0       3.0  169.0        8.0  

[5630 rows x 34 columns]

In [20]:
data_x=pd.get_dummies(final_dataset)
data_x

CustomerID  HourSpendOnApp  NumberOfDeviceRegistered  SatisfactionScore  \
0          50001             3.0                         3                  2   
1          50002             3.0                         4                  3   
2          50003             2.0                         4                  3   
3          50004             2.0                         4                  5   
4          50005             NaN                         3                  5   
...          ...             ...                       ...                ...   
5625       55626             3.0                         2                  1   
5626       55627             3.0                         5                  5   
5627       55628             3.0                         2                  4   
5628       55629             4.0                         5                  4   
5629       55630             3.0                         2                  3   

      WarehouseToHome  NumberOfAddress  Complain  OrderAmountHikeFromlastYear  \
0                 6.0                9         1                         11.0   
1                 8.0                7         1                         15.0   
2                30.0                6         1                         14.0   
3                15.0                8         0                         23.0   
4                12.0                3         0                         11.0   
...               ...              ...       ...                          ...   
5625             30.0                6         0                         18.0   
5626             13.0                6         0                         16.0   
5627             11.0                3         1                         21.0   
5628              9.0                4         0                         15.0   
5629             15.0                4         0                         13.0   

      CouponUsed  OrderCount  ...  PreferredPaymentMode_E wallet  \
0            1.0         1.0  ...                              0   
1            0.0         1.0  ...                              0   
2            0.0         1.0  ...                              0   
3            0.0         1.0  ...                              0   
4            1.0         1.0  ...                              0   
...          ...         ...  ...                            ...   
5625         1.0         2.0  ...                              0   
5626         1.0         2.0  ...                              0   
5627         1.0         2.0  ...                              0   
5628         2.0         2.0  ...                              0   
5629         2.0         2.0  ...                              0   

      PreferredPaymentMode_UPI  Gender_Female  Gender_Male  \
0                            0              1            0   
1                            1              0            1   
2                            0              0            1   
3                            0              0            1   
4                            0              0            1   
...                        ...            ...          ...   
5625                         0              0            1   
5626                         0              0            1   
5627                         0              0            1   
5628                         0              0            1   
5629                         0              0            1   

      PreferedOrderCat_Fashion  PreferedOrderCat_Grocery  \
0                            0                         0   
1                            0                         0   
2                            0                         0   
3                            0                         0   
4                            0                         0   
...                        ...                       ...   
5625                         0                         0   
5626              

In [21]:
data_x.keys()

Index(['CustomerID', 'HourSpendOnApp', 'NumberOfDeviceRegistered',
       'SatisfactionScore', 'WarehouseToHome', 'NumberOfAddress', 'Complain',
       'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount',
       'DaySinceLastOrder', 'CashbackAmount', 'Tenure', 'Churn',
       'PreferredLoginDevice_Computer', 'PreferredLoginDevice_Mobile Phone',
       'PreferredLoginDevice_Phone', 'MaritalStatus_Divorced',
       'MaritalStatus_Married', 'MaritalStatus_Single',
       'PreferredPaymentMode_CC', 'PreferredPaymentMode_COD',
       'PreferredPaymentMode_Cash on Delivery',
       'PreferredPaymentMode_Credit Card', 'PreferredPaymentMode_Debit Card',
       'PreferredPaymentMode_E wallet', 'PreferredPaymentMode_UPI',
       'Gender_Female', 'Gender_Male', 'PreferedOrderCat_Fashion',
       'PreferedOrderCat_Grocery', 'PreferedOrderCat_Laptop & Accessory',
       'PreferedOrderCat_Mobile', 'PreferedOrderCat_Mobile Phone',
       'PreferedOrderCat_Others'],
      dtype='object')

In [22]:
final_data_x = pd.DataFrame(x, columns=['PreferredLoginDevice_Computer', 'PreferredLoginDevice_Mobile Phone',
       'PreferredLoginDevice_Phone', 'MaritalStatus_Divorced',
       'MaritalStatus_Married', 'MaritalStatus_Single',
       'PreferredPaymentMode_CC', 'PreferredPaymentMode_COD',
       'PreferredPaymentMode_Cash on Delivery',
       'PreferredPaymentMode_Credit Card', 'PreferredPaymentMode_Debit Card',
       'PreferredPaymentMode_E wallet', 'PreferredPaymentMode_UPI',
       'Gender_Female', 'Gender_Male', 'PreferedOrderCat_Fashion',
       'PreferedOrderCat_Grocery', 'PreferedOrderCat_Laptop & Accessory',
       'PreferedOrderCat_Mobile', 'PreferedOrderCat_Mobile Phone',
       'PreferedOrderCat_Others','CustomerID', 'HourSpendOnApp', 'NumberOfDeviceRegistered',
       'SatisfactionScore', 'WarehouseToHome', 'NumberOfAddress', 'Complain',
       'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount',
       'DaySinceLastOrder', 'CashbackAmount', 'Tenure',])

In [23]:
final_data_x.head(5)

PreferredLoginDevice_Computer PreferredLoginDevice_Mobile Phone  \
0                           0.0                               1.0   
1                           0.0                               0.0   
2                           0.0                               0.0   
3                           0.0                               0.0   
4                           0.0                               0.0   

  PreferredLoginDevice_Phone MaritalStatus_Divorced MaritalStatus_Married  \
0                        0.0                    0.0                   0.0   
1                        1.0                    0.0                   0.0   
2                        1.0                    0.0                   0.0   
3                        1.0                    0.0                   0.0   
4                        1.0                    0.0                   0.0   

  MaritalStatus_Single PreferredPaymentMode_CC PreferredPaymentMode_COD  \
0                  1.0                     0.0                      0.0   
1                  1.0                     0.0                      0.0   
2                  1.0                     0.0                      0.0   
3                  1.0                     0.0                      0.0   
4                  1.0                     1.0                      0.0   

  PreferredPaymentMode_Cash on Delivery PreferredPaymentMode_Credit Card  ...  \
0                                   0.0                              0.0  ...   
1                                   0.0                              0.0  ...   
2                                   0.0                              0.0  ...   
3                                   0.0                              0.0  ...   
4                                   0.0                              0.0  ...   

  SatisfactionScore WarehouseToHome NumberOfAddress Complain  \
0               2.0             6.0             9.0      1.0   
1               3.0             8.0             7.0      1.0   
2               3.0            30.0             6.0      1.0   
3               5.0            15.0             8.0      0.0   
4               5.0            12.0             3.0      0.0   

  OrderAmountHikeFromlastYear CouponUsed OrderCount DaySinceLastOrder  \
0                        11.0        1.0        1.0               5.0   
1                        15.0        0.0        1.0               0.0   
2                        14.0        0.0        1.0               3.0   
3                        23.0        0.0        1.0               3.0   
4                        11.0        1.0        1.0               3.0   

  CashbackAmount     Tenure  
0          160.0        4.0  
1          121.0  10.189899  
2          120.0  10.189899  
3          134.0        0.0  
4          130.0        0.0  

[5 rows x 34 columns]

# Splitting the dataset into the training set and test set

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(final_data_x, y, test_size=0.2, random_state = 0 )

In [25]:
x_train1 = pd.DataFrame(data=x_train)

# Standard Scalar is used to transform the features into the Scalar -3 to 3

In [26]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train1 = sc.fit_transform(x_train[['CashbackAmount','Tenure']])
x_test1 = sc.transform(x_test[['CashbackAmount','Tenure']])

In [27]:
x_test1

array([[-0.99652245, -0.49222011],
       [-0.58706615,  0.47440608],
       [ 1.64447068,  0.23274953],
       ...,
       [ 0.9893406 ,  0.35357781],
       [-1.28314186,  0.0140382 ],
       [-0.52564771, -1.09636148]])

# Model Devlopment

# Logistic Regression

In [28]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [29]:
y_pred = classifier.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


Confusion matrix

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[918  21]
 [139  48]]


0.8579040852575488

# K-Nearest Neighbors(K-NN)

In [32]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [33]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Confusion matrix

In [35]:
cm = confusion_matrix( y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[903  36]
 [174  13]]


0.8134991119005328

# Support Vector Machine

In [36]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [37]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [38]:
cm = confusion_matrix( y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[937   2]
 [176  11]]


0.8419182948490231

# Kernel SVM

In [39]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(random_state=0)

In [40]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [41]:
cm = confusion_matrix( y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[939   0]
 [187   0]]


0.8339253996447602

# Naive Bayes

In [42]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [43]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [1 0]]


In [44]:
cm = confusion_matrix( y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[725 214]
 [ 74 113]]


0.7442273534635879

# Decision Tree Classification

In [45]:
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
model_dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [46]:
y_pred_dt = model_dt.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [1 0]]


In [47]:
cm = confusion_matrix( y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[725 214]
 [ 74 113]]


0.7442273534635879

In [48]:
from sklearn.metrics import classification_report

In [49]:
print(classification_report(y_test,y_pred_dt, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.97      0.96      0.97       939
           1       0.82      0.83      0.83       187

    accuracy                           0.94      1126
   macro avg       0.90      0.90      0.90      1126
weighted avg       0.94      0.94      0.94      1126



In [50]:
pip install imblearn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [51]:
from imblearn.combine import SMOTEENN

In [52]:
sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(final_data_x, y)

In [53]:
xr_train, xr_test, yr_train, yr_test = train_test_split(x_resampled, y_resampled, test_size = 0.2) 

In [54]:
model_dt_smote = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)

In [55]:
model_dt_smote.fit(xr_train, yr_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [56]:
y_pred_smote = model_dt_smote.predict(xr_test)

In [57]:
print(classification_report(yr_test,y_pred_smote, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.97      0.94      0.95       455
           1       0.96      0.98      0.97       747

    accuracy                           0.97      1202
   macro avg       0.97      0.96      0.96      1202
weighted avg       0.97      0.97      0.97      1202



In [58]:
print(confusion_matrix(yr_test, y_pred_smote))

[[427  28]
 [ 13 734]]


In [59]:
print(accuracy_score(yr_test,y_pred_smote))

0.9658901830282862


its now a balance dataset,perform smart analysis

# Random Forest

In [60]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [61]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


In [62]:
cm = confusion_matrix( y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[931   8]
 [ 67 120]]


0.933392539964476

In [63]:
sm = SMOTEENN()
x_resampled_rf, y_resampled_rf = sm.fit_resample(final_data_x, y)

In [64]:
xrf_train, xrf_test, yrf_train, yrf_test = train_test_split(x_resampled_rf, y_resampled_rf, test_size = 0.2) 

In [65]:
from sklearn.ensemble import RandomForestClassifier
model_rf_smote = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)

In [66]:
model_rf_smote.fit(xrf_train, yrf_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [67]:
y_pred_smote_rf = model_rf_smote.predict(xrf_test)

In [68]:
print(classification_report(yrf_test,y_pred_smote_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96       430
           1       0.99      0.96      0.98       785

    accuracy                           0.97      1215
   macro avg       0.96      0.97      0.97      1215
weighted avg       0.97      0.97      0.97      1215



In [69]:
print(confusion_matrix(yrf_test, y_pred_smote_rf))
print(accuracy_score(yrf_test,y_pred_smote_rf))

[[421   9]
 [ 28 757]]
0.9695473251028807


# Model Development
Firstly I will split the data into training and testing samples. I will make pipelines which will include all the preprocessing steps and the classifier. I will use 7 Classifiers; 4 linear classifiers,1 Non-linear classifiers, 2 tree classifiers to build the model. I will perform cross validation on the training samples, and use prediction of the testing sample to compare the models, and select the best model for hyperparameter tuning.

# Save the modle

In [71]:
import pickle

In [72]:
filename = 'Model.sav'

In [73]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [74]:
load_model = pickle.load(open(filename, 'rb'))

In [75]:
load_model.score(xrf_test, yrf_test)

0.9695473251028807